//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyam_Nyam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookStage
    {
        public string Id { get; set; }
        public string DishId { get; set; }
        public string Description { get; set; }
        public string Minutes { get; set; }
    }
}
